# Generated by Django 5.1.3 on 2025-01-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_useremailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to="auth_api.user"),
        ),
    ]
