# Generated by Django 5.1.3 on 2024-12-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_useremailverification"),
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to="auth_api.user",
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user2",
                to="auth_api.user",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="auth_api.user",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="auth_api.user",
            ),
        ),
    ]
