# Generated by Django 5.1.3 on 2025-01-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0002_alter_friend_user1_alter_friend_user2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friend",
        ),
    ]
