# Generated by Django 5.1.3 on 2025-01-02 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_api", "0002_useremailverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=500)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_api.user"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="members", to="auth_api.user"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
