# Generated by Django 5.1.3 on 2025-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
